POST http://localhost:8080/api/twitterpfp
Content-Type: application/json

{
  "screenName": "@GovInslee"
}

###
POST http://localhost:8080/api/keywords
Content-Type: application/json

{
  "screenName": "@GovInslee",
  "numKeywords": 15
}

###
